# File: analysis_options.yaml
# Purpose: Configure static analysis for the MidRange OpsHub Flutter app
# ───────────────────────────────────────────────────────────────────────────
# CHANGELOG:
# [2025-05-06] Initial commit using flutter_lints with placeholders for customization.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # === Customizable Rules Below ===
    # avoid_print: false               # Uncomment to allow print statements
    # prefer_single_quotes: true      # Uncomment to enforce single quotes
    # always_use_package_imports: true  # Encourage consistent package imports
    # require_trailing_commas: true     # Helpful for clean diffs in Flutter UIs
    # sort_pub_dependencies: true       # Enforces pubspec.yaml sorting