# File: pubspec.yaml
# Purpose: Defines project metadata, dependencies, and asset references for MidRange OpsHub
# ───────────────────────────────────────────────────────────────────────────
# CHANGELOG:
# [2025-05-06] Initial baseline with flutter_lints, logo asset, and core setup for screen routing.
# [2025-05-07] Added dotenv for environment variables and http package for network requests.
# [2025-05-08] Updated dependencies to latest versions and added comments for clarity.


name: midrange_ops_hub
description: MidRange OpsHub mobile companion app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/nov_logo.png